[package]
name = "bees-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = "*"
proc-macro2 = "*"
quote = "1.0.44"
proc-macro-crate = "3.4.0"

[lib]
proc-macro = true


[profile.release]
opt-level = 3
